[project]
name = "mintlab"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "jupyterlab>=4.4.10",
    "jupytext==1.18.1",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
]
